
# -- Basics --
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g mouse on
set -g mode-keys vi

# -- Prefix Key --
unbind C-b
set -g prefix M-a
bind M-a send-prefix

# -- Splits --
bind | split-window -h
bind - split-window -v

# -- Reload config --
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Use vi keys in copy mode
set -g mode-keys vi

# -- Set history scroll limit to 10000
set -g history-limit 10000

# Explicitly bind Vim-style selection keys
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle

set -g set-clipboard on
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
